name: grader
dependencies:
- dill=0.2.3=py27_0
- flake8=2.3.0=py27_0
- jsonschema=2.4.0=py27_0
- mccabe=0.3=py27_1
- nose=1.3.7=py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py27_0
- pep8=1.6.2=py27_0
- pip=7.1.0=py27_0
- py=1.4.30=py27_0
- pyflakes=0.9.2=py27_0
- pyparsing=2.0.3=py27_0
- pytest=2.7.2=py27_0
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- readline=6.2=2
- requests=2.7.0=py27_0
- scikit-learn=0.16.1=np19py27_0
- scipy=0.16.0=np19py27_0
- setuptools=18.0.1=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- toolz=0.7.2=py27_0
- ujson=1.33=py27_0
- zlib=1.2.8=0
- pip:
  - amqp==1.4.6
  - anyjson==0.3.3
  - billiard==3.3.0.20
  - celery==3.1.18
  - docker-py==1.3.1
  - kombu==3.0.26
  - redis==2.10.3
  - tabulate==0.7.5
  - websocket-client==0.32.0

